[".config/zsh/plugins/zsh-autocomplete"]
  type = "git-repo"
  url = "https://github.com/marlonrichert/zsh-autocomplete"
  clone.args = ["--depth", "1"]
  pull.args = ["--ff-only"]

[".config/zsh/plugins/zsh-completions"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-completions.git"
  clone.args = ["--depth", "1"]
  pull.args = ["--ff-only"]

[".config/zsh/plugins/zsh-syntax-highlighting"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  clone.args = ["--depth", "1"]
  pull.args = ["--ff-only"]
