require("config.globals")
require("config.commands")
require("config.options")
require("config.mappings")
require("config.lsp")

require("plugin.vague")
require("plugin.telescope")
require("plugin.mason")
require("plugin.fidget")
require("plugin.neotree")
require("plugin.conform")
require("plugin.smart-splits")
require("plugin.render-markdown")
require("plugin.treesitter")
