#!/usr/bin/env zsh
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

[[ -f "${ZDOTDIR}/.zshwork" ]] && source "${ZDOTDIR}/.zshwork"
[[ -f "${ZDOTDIR}/.zshenv" ]] && source "${ZDOTDIR}/.zshenv"
