# https://github.com/marlonrichert/zsh-autocomplete
if [[ -f $ZDOTDIR/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh ]]; then
  . $ZDOTDIR/plugins/zsh-autocomplete/zsh-autocomplete.plugin.zsh
fi

# emacs keybindings
bindkey -e

# https://github.com/zsh-users/zsh-syntax-highlighting
if [[ -f $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh ]]; then
  . $ZDOTDIR/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
fi

# Taken from https://github.com/Phantas0s/.dotfiles/blob/master/zsh/zshrc
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.

# Homebrew for OSX

if [[ -f /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if [[ -d /opt/homebrew/opt/coreutils/libexec/gnubin ]]; then
  PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:$PATH"
  MANPATH="/opt/homebrew/opt/coreutils/libexec/gnuman:$MANPATH"
fi

# LS_COLORS themes with vivid
# https://github.com/sharkdp/vivid
export LS_COLORS="$(vivid generate nord)"

if [[ -d $HOME/.asdf ]]; then
  export ASDF_DATA_DIR="$HOME/.asdf"
  export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
fi

# Load when installed via ARCH aur package
if [[ -f /opt/asdf-vm/asdf.sh ]]; then
  . "/opt/asdf-vm/asdf.sh"
fi

if [[ -f /opt/homebrew/opt/asdf/libexec/asdf.sh ]]; then
  . "/opt/homebrew/opt/asdf/libexec/asdf.sh"
fi

# Aliases
alias ls="ls --color=always"
alias vim="nvim"
alias vi="nvim"

# https://github.com/ajeetdsouza/zoxide
eval "$(zoxide init zsh)"

# https://starship.rs/
eval "$(starship init zsh)"

if command -v fastfetch 2>&1 >/dev/null; then
  fastfetch
fi
