$bg       = rgb({{colors.surface.default.hex_stripped}})
$fg       = rgb({{colors.on_surface.default.hex_stripped}})
$accent   = rgb({{colors.primary.default.hex_stripped}})
$muted    = rgb({{colors.outline.default.hex_stripped}})
